name: Autograding

on:
  # Run autograding when there's a push or pull request to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  autograding:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the tests using pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings

      # Step 5: Save test results for later use
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results
          path: pytest-results.xml
